canvas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
url(r'^$', views.home, name ='home'),
url(r'^create_canvas_post/(?P<canvas_id>[0-9]+)$', views.create_canvas_post , name ='create_canvas_post'),
url(r'^delete_canvas_post/(?P<canvas_id>[0-9]+)$', views.delete_canvas_post , name = 'delete_canvas_post'),
url(r'^check/$', views.check, name ='check'),
]

humour/urls.py
from django.conf.urls import include, url
from django.contrib import admin



from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^humour/' , include('userprofile.urls',namespace="userprofile")),
    url(r'^humour/home/' , include('canvas.urls', namespace="canvas")),
    url(r'^base/$', views.base, name ='base'),

]

userprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
url(r'^$', views.loginpage, name ='loginpage'),
url(r'^userprofile/$', views.profile, name ='profile' ),
url(r'^logging_in/$', views.login_user, name ='login_user' ),
url(r'^logging_out/$', views.logout_user, name= 'logout_user'),
url(r'^(?P<user_id>[0-9]+)/users/$' ,views.other_userpofile, name= 'other_userpofile'),
]

canvas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

class Canvas(models.Model):
	user= models.ForeignKey(User)
	parent = models.ManyToManyField("self", symmetrical=False , related_name='children')
	canvas_post = models.CharField(max_length=400)
	pub_date = models.DateTimeField('date published')
	# post_font= models.CharField(max_length=100, default="Arial")
	# font_size= models.PositiveIntegerField(validators=[MinValueValidator(6),
 #                                    MaxValueValidator(100)], default=12)
	# post_color= models.CharField(max_length=100, default="black")

	def __str__(self):
		return self.canvas_post

	def last_child_canvas(self):
		 return self.children.order_by('pub_date')[:1]

	def canvas_recursive_delete(self, canvas_id):
		""" Deltes the all of the children of the parent with 
		 the corrosponding canvas_id and then deletes the parent

		"""
		canvas_obj_to_del = Canvas.objects.filter(id=canvas_id)

		if canvas_obj_to_del[0].children.all() :
			canvas_obj_to_del[0].children.all().delete()
		
		canvas_obj_to_del.delete()

		return None




class Texts_In_Canvas(models.Model):
	canvas = models.ForeignKey(Canvas)
	canvas_text = models.CharField(max_length=200)
	coordinates_x = models.IntegerField(default=0)
	coordinates_y = models.IntegerField(default=0)
	text_font= models.CharField(max_length=100, default="Arial")
	text_size= models.PositiveIntegerField(validators=[MinValueValidator(6),
                                    MaxValueValidator(100)], default=12)
	text_color= models.CharField(max_length=100, default="black")
	

	def __str__(self):
		return self.canvas_text

canvasdraw/models.py
from django.db import models

# Create your models here.

canvasimage/models.py
from django.db import models

# Create your models here.

canvaswrite/models.py
from django.db import models

# Create your models here.

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from annoying.fields import AutoOneToOneField




class UserProfile(models.Model):
	user = AutoOneToOneField(User)
	follows = models.ManyToManyField('UserProfile', related_name='followed_by')

	def __str__(self):
		return self.user.username


class UserMethods(User):

	def canvas_ids_list(self):
		canvasids = []
		for canvas in self.canvas_set.all():
			canvasids.append(canvas.id)

		return canvasids

	class Meta:
		proxy=True

canvas/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse 
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from userprofile.models import UserProfile, UserMethods
from . models import Canvas
from django.contrib.auth.models import User
from django.utils import timezone  



@login_required(login_url='/humour/')
def home(request):
	
	user_canvas_ids = UserMethods.canvas_ids_list(request.user)
	user_canvas_set = request.user.canvas_set.all().order_by('-pub_date')
	data= {'user_canvas_set':user_canvas_set, 'user_canvas_ids':user_canvas_ids }
	return render(request, 'canvas/home.html' ,data)


def check(request):
	h = "what"

	return render(request, 'canvas/check.html' )

# def create_canvas_post(request, canvas_id):
# 	if request.method == 'POST':
# 		canvas_post_text = request.POST.get('canvas_post')
# 		font_size = request.POST.get('font_size')
# 		post_font = request.POST.get('post_font')
# 		canvas_post_obj = request.user.canvas_set.create(canvas_post= canvas_post_text, 
# 		pub_date= timezone.now(), font_size= font_size, post_font= post_font)
# 		canvas_post_obj.save()

# 		data = {}
# 		data['something'] = 'useful'
    
# 		if canvas_id == '0' :
# 			pass	

		
# 		else:	
# 			parent_canvas_obj = Canvas.objects.get(id=canvas_id)
# 			parent_canvas_obj.children.add(canvas_post_obj)

# 	return HttpResponse(json.dumps(data), content_type = "application/json")

	
def create_canvas_post(request, canvas_id):
	if request.method == 'POST':
		
		data = {}
 		
		canvas_text = request.POST.getlist('canvas_text[]')
		text_size = request.POST.getlist('text_size[]')
		text_font = request.POST.getlist('text_font[]')
		text_color = request.POST.getlist('text_color[]')
		text_opacity = request.POST.getlist('text_opacity[]')
		text_y_pos= request.POST.getlist('text_y_pos[]')
		text_x_pos = request.POST.getlist('text_x_pos[]')


		

		data['text'] = text_size[0]

		canvas_obj = request.user.canvas_set.create(canvas_post= "man", 
  		pub_date= timezone.now())

		canvas_obj.save()
		
			
		for i  in range(len(canvas_text)):

			canvas_obj.texts_in_canvas_set.create(canvas_text= canvas_text[i], 
  			text_font= text_font[i], 
  			text_size= int(text_size[i]),
  			coordinates_x=int(text_x_pos[i]), coordinates_y=int(text_y_pos[i]),
  			text_color = text_color[i]
  			)  
  		
  		
		if canvas_id == '0' :
			pass	
		else:	
			parent_canvas_obj = Canvas.objects.get(id=canvas_id)
			parent_canvas_obj.children.add(canvas_obj)

		
	
	return HttpResponse(json.dumps(data), content_type = "application/json")



def delete_canvas_post(request, canvas_id):
	Canvas().canvas_recursive_delete(canvas_id)

	
	return HttpResponseRedirect(reverse('canvas:home' )) 


def show_more_comments(request):
	pass

canvasdraw/views.py
from django.shortcuts import render

# Create your views here.

canvasimage/views.py
from django.shortcuts import render

# Create your views here.

canvaswrite/views.py
from django.shortcuts import render

# Create your views here.

humour/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse 




def base(request):
	h = "what"

	return render(request, 'humour/base.html' )

userprofile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse 
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from django.contrib.auth.models import User


@login_required(login_url='/humour/')
def profile(request):
	user= request.user
	following = user.userprofile.follows.all()
	data = {'following':following}

	return render(request, 'userprofile/profile.html', data)
		
def other_userpofile(request, user_id):
    return HttpResponse(user_id)


def loginpage(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('userprofile:profile' )) 
		
	else:
		return render(request, 'userprofile/loginpage.html')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('userprofile:loginpage' ))     


def login_user(request):
	username = request.POST['username']
	password = request.POST['password'] 
	user = authenticate(username=username, password=password)
	if user is not None and user.is_active:
        	login(request, user)
        	return HttpResponseRedirect(reverse('userprofile:profile' ))        
	else:
		return HttpResponse("invald login")


	

	

canvas/templates/canvas/canvas_comments.html
 <a href="id" class="more_commentslink" >more comments </a>
<p ><a class = "child_canvas_user_name" href="{% url 'userprofile:other_userpofile' canvas_children.user.id %}">{{ canvas_children.user }}</a></p>


<canvas id="{{canvas_children.id}}" class = "child_canvases"  data-post-font-size = "{{canvas_children.font_size}}" data-post-font= "{{canvas.post_font}}" 
canvas_post= "{{canvas_children.canvas_post}}" >
Your browser does not support the HTML5 canvas tag.</canvas>

canvas/templates/canvas/canvascreate.html
<!--   <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="{{ STATIC_URL }}/static/jquery-mobile/themes/blue.css">
<link rel="stylesheet" href="{{ STATIC_URL }}/static/jquery-mobile/themes/jquery.mobile.icons.min.css">

<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile.structure-1.4.5.min.css" />
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
 -->



{% include "canvas/common_toolbox.html" %} 

<div class="main_navbar_div">


<button class = "canvaswrite_but" id="{{ref_canvas_id}}canvaswrite_but"  data-ref-canvas-id="{{ref_canvas_id}}"  style="width:105px; height:30px">TEXT</button>

<button class = "canvasdraw_but" id="{{ref_canvas_id}}canvasdraw_but" data-ref-canvas-id="{{ref_canvas_id}}" style="width:105px; height:30px" >DRAW</button>

<button class = "canvasimage_but" id="{{ref_canvas_id}}canvasimage_but" data-ref-canvas-id="{{ref_canvas_id}}"  style="width:107px; height:30px" >IMAGE</button>

<button class = "canvasvideo_but" id="{{ref_canvas_id}}canvasvideo_but" data-ref-canvas-id="{{ref_canvas_id}}" data-toolbox="canvasvideo_toolbox" style="width:105px; height:30px" >VIDEO</button>

<button class = "canvassound_but" id="{{ref_canvas_id}}canvassound_but" data-ref-canvas-id="{{ref_canvas_id}}" data-toolbox="canvassound_toolbox" style="width:105px; height:30px" >SOUND</button>




<input type="hidden" id="{{ref_canvas_id}}colour"  class="form-control demo" data-control="hue" value="#000000" >


<button type="button" data-ref-canvas-id="{{ref_canvas_id}}" class="add_layer" id="{{ref_canvas_id}}add_layer" value="+ layer" style="width:65px; height:25px" > +layer</button>




<button id="{{ref_canvas_id }}layers_button" data-layers-dialog-id="{{ref_canvas_id }}layer_dialog" data-ref-canvas-id="{{ref_canvas_id}}" class="layers_button" style="width:230px; height:25px">layers</button>

</div>




<div class="layers_dialog" id="{{ref_canvas_id}}layer_dialog"
 title="layers" >

	<div class="layers" id="{{ref_canvas_id}}layers"   >


	</div>  
</div>



<div class="canvas_layers" id="{{ref_canvas_id}}canvas_layers" 
data-ref-canvas-id ="{{ref_canvas_id}}" >
<!-- put all the layers here including backbround   must be made auto beucsase
of all the divs and attrubites-->
<div id="{{ref_canvas_id}}div_layer0" class="div_layer" data-zindex="2" style="width:550px; height:275px; z-index:2;  position:static;" >

	<canvas class="layer" data-zindex="2" id="{{ref_canvas_id}}layer0" 
	data-ref-canvas-id="{{ref_canvas_id}}" style="width:550px; height:275px; z-index:2 ;
	border: 0px; "> </canvas>

</div>

<form   id= "{{canvas_html_input_id }}canvas_form" class="canvas_form" data-ref-canvas-id ="{{canvas_html_input_id }}"   >


	<input  class= "canvas_post_button" type="submit" data-ref-canvas-id ="{{canvas_html_input_id }}"  value="post"  />
</form>
</div>






<div class= "canvascreate_container">

	



	<div class= "backgroundtab" >
		<!-- make  the canvas create the main canvas- background white   -->
		
		<canvas  class = "canvas_background"   >
		Your browser does not support the HTML5 canvas tag.</canvas>

	</div> 


	<div class="canvaswritetab"  data-toolbox="canvaswrite_toolbox" 
	id="{{ref_canvas_id}}canvaswritetab">
			{% include "canvaswrite/canvaswrite_gui.html" with canvas_html_input_id=ref_canvas_id %}
	</div>
		
	<div class="canvasdrawtab"  data-toolbox="canvasdraw_toolbox" id="{{ref_canvas_id}}canvasdrawtab">
		{% include "canvasdraw/canvasdraw_gui.html" with ref_canvas_id=ref_canvas_id %}
	</div>

	<div class="canvasimagetab" data-toolbox="canvasimage_toolbox" id="{{ref_canvas_id}}canvasimagetab">
		{% include "canvasimage/canvasimage_gui.html" with ref_canvas_id=ref_canvas_id %}
	</div>

</div>

<script>
$("button").button();

//alert("{{ref_canvas_id}}");




$(".layers_button").button();



  var colpick = $('.demo').each( function() {
    $(this).minicolors({
      control: $(this).attr('data-control') || 'hue',
      inline: $(this).attr('data-inline') === 'true',
      letterCase: 'lowercase',
      
      opacity: true,
      change: function(hex, opacity) {
        if(!hex) return;
       
        try {
          console.log(hex + "  " + opacity);
        } catch(e) {}
        $(this).select();
      },
      //theme: 'bootstrap'
    });
  });


</script>

canvas/templates/canvas/check.html
{% extends "canvas/home.html" %}


{% block title %}My amazing canvaswrite{% endblock %}

canvas/templates/canvas/common_toolbox.html
<div class= "common_toolbox">

	<label class="move" data-ref-canvas-id="{{ref_canvas_id}}"  id="{{ref_canvas_id}move" style="width:20px" > </label>


	<label class="cut" data-ref-canvas-id="{{ref_canvas_id}}"  id="{{ref_canvas_id}cut" style="width:20px" > </label>



	

</div>  





<script>
 $( ".move" ).button({
 	icons:{
 		primary:"ui-icon-arrow-4"
 	}

 } );

 $( ".cut" ).button({
 	icons:{
 		primary:"ui-icon-scissors"
 	}

 } );




 

 
//
</script>

canvas/templates/canvas/home.html
<!DOCTYPE html>

{% load static from staticfiles %}
<html>
<head>
	


	<link rel="stylesheet" href="{% static 'canvas/style/styles.css' %}" type="text/css"> 
	<link rel="stylesheet" href="{% static 'canvas/style/buttons.css' %}" type="text/css"> 
	
	<link rel="stylesheet" href="{{ STATIC_URL }}/static/jquery-ui-1.11.4.custom/jquery-ui.min.css">



	<script type="text/javascript" src="{{ STATIC_URL }}/static/jquery-1.11.3.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}/static/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>



	<script type="text/javascript" src="{% static 'canvaswrite/js/canvaswrite_render.js' %}"></script>


	<!-- canvas js -->
	<script type="text/javascript" src="{% static 'canvas/canvas_comment_button.js' %}"></script>
	<script type="text/javascript" src="{% static 'canvas/js/create_gui_settings.js' %}"></script>
	<script type="text/javascript" src="{% static 'canvas/js/canvascreate.js' %}"></script>



	<!-- for colour picker -->
	<link rel="stylesheet" href="{{ STATIC_URL }}/static/css/jquery.minicolors.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}/static/css/bootstrap.min.css"> 
	<script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery.minicolors.min.js"></script>

	<!-- canvasdraw -->

	<script type="text/javascript" src="{% static 'canvasdraw/js/canvasdraw.js' %}"></script>

<!-- canvasimage -->
	<script type="text/javascript" src="{% static 'canvasimage/js/canvasimage.js' %}"></script>




</head>

<body>




	<!--  <h1>{% block title %}My amazing site{% endblock %}</h1> -->


<div class= "center_column">

	

	 	{% include "canvas/canvascreate.html" with ref_canvas_id=0 %}

	 

	





   	{% for canvas in user_canvas_set %}


   		{% if canvas.texts_in_canvas_set.all %}

<!-- all the meta data of text data  -->
   		<div class= "incanvas_text_data" 
   		 data-ref-canvas-id="{{canvas.id}}" >

	   	{% for text in canvas.texts_in_canvas_set.all %}
	   
	   
	   	<p 
	   	data-font="{{text.text_font}}"
	   	  data-font-size="{{text.text_size }}"
	   	 data-color="{{text.text_color}}"
	   	 data-x-pos="{{text.coordinates_x}}"
	   	 data-y-pos="{{text.coordinates_y}}"
	   	 data-opacity="1" 
	   	 data-text="{{text.canvas_text}}">
	   	</p>

	   	{% endfor %}



	    </div>
	    {% endif  %}
	   	




	    {% if not canvas.parent.all %}



		<p class= "canvas_heading"> 
			{{canvas.user}}   {{canvas.pub_date}}  <a class= "delete_post_link" href="{% url 'canvas:delete_canvas_post' canvas.id %}" >delete</a>
		 </p> 

		<canvas  class = "canvas" id="{{canvas.id}}"
		canvas_post= "{{canvas.canvas_post}}" data-post-font-size = "{{canvas.font_size}}"
		data-post-font= "{{canvas.post_font}}" >
		Your browser does not support the HTML5 canvas tag.</canvas>

			    
		    {%if not canvas.last_child_canvas %}
				<button class= "canvas_comment_button"  > comment </button>
				<div class= "comment_canvas"  > 
				{% include "canvas/canvascreate.html" with ref_canvas_id=canvas.id %}
			
				
			
				</div>
			{% endif %}

		{% endif %}	

		
			{%for canvas_children in canvas.last_child_canvas %}		
				{% include "canvas/canvas_comments.html" %}
			{% endfor %}



	{% endfor %}
	
</div>

</body>

	<script type="text/javascript" src="{% static 'canvaswrite/js/canvaswrite_post.js' %}"></script>
	<script type="text/javascript" src="{% static 'canvaswrite/js/canvaswrite.js' %}"></script>


</html>

	

canvasdraw/templates/canvasdraw/canvasdraw_gui.html
{% load static from staticfiles %}

<link rel="stylesheet" href="{% static 'canvasdraw/style/css_canvasdraw.css' %}" type="text/css"> 

<div class = "canvasdraw_toolbox" id="{{ref_canvas_id}}canvasdraw_toolbox" 
data-selected-tool="draw">
	<p>  canvasdraw </p>

<!-- 	<input type="button" data-ref-canvas-id="{{ref_canvas_id}}" class="add_draw" id="{{ref_canvas_id}add_draw" value="+ layer"> -->

<!-- 	<input type="button" class="move" data-ref-canvas-id="{{ref_canvas_id}}"  id="{{ref_canvas_id}move" value="move"> -->






	<select class= "draw_tool_selector"  id="draw_tool_selector{{ref_canvas_id}}"  
	data-ref-canvas-id="{{ref_canvas_id}}" >
  <option value="Draw">Draw</option>
  <option value="Rectangle">Rectangle </option>
  <option value="Circle">Circle</option>
  <option value="line">Line</option>
 </select>
</div>

<div class= "canvas_draw_div" id = "{{ref_canvas_id}}canvas_draw_div" >

<!-- <canvas  class = "canvas_create" id="{{ref_canvas_id}}canvasdraw"  >
Your browser does not support the HTML5 canvas tag.</canvas><br> -->

</div>

canvasimage/templates/canvasimage/canvasimage_gui.html
{% load static from staticfiles %}

<link rel="stylesheet" href="{% static 'canvasimage/style/css_canvasimage.css' %}" type="text/css"> 

<div class = "canvasimage_toolbox" id="{{ref_canvas_id}}canvasimage_toolbox">
<h1>  canvas image draw </h1> 


<input class= "image_source" id="{{ref_canvas_id}}image_source" value ="http://i.ytimg.com/vi/fu1lRZqeNX0/maxresdefault.jpg"/> 
<button class="add_image" id="{{ref_canvas_id}}add_image" data-ref-canvas-id ="{{ref_canvas_id}}" > add image </button> 

</div>
<canvas  class = "canvas_create" id="2canvasimage"  >
Your browser does not support the HTML5 canvas tag.</canvas><br>

canvaswrite/templates/canvaswrite/canvaswrite_gui.html
{% load staticfiles %}

<!--<script type="text/javascript" src="{% static 'canvas/ajax_canvas_post.js' %}"></script>-->
<head>


<link rel="stylesheet" href="{% static 'canvas/style/canvas_create_gui.css' %}" type="text/css">
 
<link rel="stylesheet" href="{% static 'canvaswrite/style/css_canvaswrite.css' %}" type="text/css">
 




</head>

<div class="canvaswrite_toolbox" id="{{canvas_html_input_id}}canvaswrite_toolbox">


<input type="button" ref_canvas_id="{{canvas_html_input_id}}" class="add_texts" id="{{canvas_html_input_id}}add_texts" value="+ text">

<select id= "{{canvas_html_input_id }}font_selector" class="font_selector"  
style="width:100px">

  <option value="Arial">Arial</option>
  <option value="Helvetic"> Helvetic</option>
  <option value="Comic Sans MS">Comic Sans MS</option>
  <option value="Times New Roman">Times New Roman</option>
  <option value="Georgia"> Georgia</option>
  <option value="Impact"> Impact</option>
</select>



<input id="{{canvas_html_input_id }}size_selector" value='15'  type="number" name="quantity" min="15" max="70" class="size_selector">


</div>
  


<!-- <div class="canvas_create_div" id = "{{canvas_html_input_id}}canvas_create_div">

<canvas  class = "canvas_create" id="{{canvas_html_input_id}}canvas"  >
Your browser does not support the HTML5 canvas tag.</canvas><br>


</div> -->

<input type="hidden" id= "{{canvas_html_input_id }}url" data-url="{% url 'canvas:create_canvas_post' canvas_html_input_id  %}" />

<!-- 
<form   id= "{{canvas_html_input_id }}canvas_form" class="canvas_form" data-ref-canvas-id ="{{canvas_html_input_id }}"   >


	<input  class= "canvas_post_button" type="submit" data-ref-canvas-id ="{{canvas_html_input_id }}"  value="post"  />
</form>
 -->

<script>

 

  // var colpick = $('.demo').each( function() {
  //   $(this).minicolors({
  //     control: $(this).attr('data-control') || 'hue',
  //     inline: $(this).attr('data-inline') === 'true',
  //     letterCase: 'lowercase',
      
  //     opacity: true,
  //     change: function(hex, opacity) {
  //       if(!hex) return;
       
  //       try {
  //         console.log(hex + "  " + opacity);
  //       } catch(e) {}
  //       $(this).select();
  //     },
  //     //theme: 'bootstrap'
  //   });
  // });





$(".canvas_post_button").button();




</script>

<!--
<script>
ajax_create_canvas("{{canvas_html_input_id }}canvas_form" ,"{{canvas_html_input_id }}" )
</script>

-->

humour/templates/humour/base.html
{% load static from staticfiles %}

<script type="text/javascript" src="{{ STATIC_URL }}/static/jquery-1.11.3.min.js"></script>

<script type="text/javascript" src="{% static 'canvas/js/canvas_create_gui/create_gui_settings.js' %}"></script>

<script type="text/javascript" src="{{ STATIC_URL }}/static/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>





	{% include "canvas/home.html"%}

userprofile/templates/userprofile/loginpage.html
<!-- 
<h3>Login</h3>

<form action="{% url 'userprofile:login_user' %}" method="post" accept-charset="utf-8">
{% csrf_token %}
<label for="username">Username</label><input type="text" name="username" value="" id="username" />

<label for="password">Password</label><input type="password" name="password" value="" id="password" />
<p><input type="submit" value="Login →"></p>
</form>
 -->
<!DOCTYPE html>
<html lang="en">
  <head>

  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="{{ STATIC_URL }}/static/css/bootstrap.min.css"> 

  <nav class="navbar navbar-inverse navbar-fixed-top">
   
    </nav>

    
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
      	<br>
      	<form  action="{% url 'userprofile:login_user' %}" method="post" accept-charset="utf-8">
			{% csrf_token %}

	      	<div class="row">
	      
	        <div class="col-md-4">. <div class="form-group">
	              <input type="text" name="username" value="" id="username" placeholder="Email" class="form-control">
	            </div></div>

	        <div class="col-md-4">.  <div class="form-group">
	              <input type="password" name="password" value="" id="password" placeholder="Password" class="form-control">
	            </div></div>
	     
	      </div>
	      <button type="submit" class="btn btn-primary btn-lg">Sign in</button>
	    </form>
        <h1>HumourUs</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>


   

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->

	<script type="text/javascript" src="{{ STATIC_URL }}/static/jquery-1.11.3.min.js"></script>

	</body>
</html>

userprofile/templates/userprofile/profile.html
<h1> {{user.username}} </h1>
<h1> follows </h1>
{% for follows_who in following %}
	<li> {{follows_who.user.username}} </li>

{% endfor %}

<form action="{% url 'userprofile:logout_user'  %}" method="post">
{% csrf_token %}
<input type="submit" , value= "logout" />

</form>